### PR TITLE
callable type hint in php 5.4

### PR DESCRIPTION
**Pull request by samsonasik**
apply callable type hint, refs https://github.com/zendframework/zf2/pull/7119

### CODE REVIEW

**Comment by Ocramius** [comment]
These changes are semver-incompatible, as the signature of the methods change.

I wouldn't mind, to be honest, but any inheritance in the affected classes would be broken in this case.

(Shameless plug: we need more [`final`](http://ocramius.github.io/blog/when-to-declare-classes-final/))

**Comment by samsonasik** [comment]
the @param type already indicate it must be callable, I don't change the @param callable|string|null as it optional. /cc @weierophinney if it is acceptable ?

**Comment by Ocramius** [comment]
@samsonasik the problem is that following code will cause a `PHP Strict standards:  Declaration of Bar::baz() should be compatible with Foo::baz(callable $baz)`:

```php
<?php

class Foo
{
    public function baz(callable $baz)
    {
    }
}

class Bar extends Foo
{
    public function baz($baz)
    {
    }
}
```

**Comment by samsonasik** [comment]
ok ;)

**Comment by Ocramius** [comment]
Closing as per review. Sorry @samsonasik, but I hope you understand what incompatibility is being introduced here.

**Comment by samsonasik** [comment]
it's ok :+1:

**Pull request closed without merging**
